import tkinter as tk
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')
suicide=pd.read_csv('suicide2001.csv')
from tkinter import *
root=tk.Tk()
root.geometry('900x700')
def first():
    def gender():
        gen=suicide.groupby('Gender')['Total'].sum()
        #print(gen)
        gen.plot(kind='bar')
        plt.title("Genderwise Analysis")
        plt.xlabel("Gender")
        plt.ylabel("Suicides")
        plt.show()
    def ageg():
        #root4=tk.Tk()
        #root.geometry('600x600')
        ages=suicide.groupby('Age_group')['Total'].sum()
        print(ages)
        ages.plot(kind='bar')
        plt.title("Age-Group wise Analysis")
        plt.xlabel("Age Groups")
        plt.ylabel("Suicides")
        plt.show()
        root.mainloop()
    def profession():
        #ages=suicide.loc[suicide['Type_code']=='Professional_Profile']['Type']['Total']
        #print(ages)
        agegr=suicide[suicide['Type_code']=='Professional_Profile']
        agegro=agegr.groupby('Type')['Type'].count()
        agegro.plot(kind='bar')
        plt.title("Profession Wise Analysis")
        plt.xlabel("Profession")
        plt.ylabel("Suicides")
        plt.show()
        '''agegr=ages.groupby('Type')['Total'].sum()
        print(agegr)'''
        #ages.plot(kind='bar')
        #plt.show()
        root.mainloop()
    def reason():
        #root3=tk.Tk()
        #root3.geometry('600x600')
        
        rea=suicide[suicide['Type_code']=='Causes']
        reas=rea.groupby('Type')['Type'].count()
        #print(reas)
        reas.plot(kind='bar')
        plt.title("No. of Suicides according to Reasons")
        plt.xlabel("Reasons")
        plt.ylabel("Suicides")
        plt.show()
        #print(rea)
        #reasonlabel=Label(master=root3,text="There are "+rea+" reasons of suicide",font=('Times New Roman',15),fg="black")#,command=year) 
        #sreasonlabel.place(x=10,y=200)
        root.mainloop()

    def state():
        def analysis():
            def stategraph():
                tog=pun.groupby('Year')['Total'].sum()
                #print(tog)
                tog.plot(kind='bar')
                plt.title("Statewise Analysis of Suicide State")
                plt.xlabel("States")
                plt.ylabel("Suicides")
                plt.show()
                root.mainloop()
            entered=(statese.get())
            pun=suicide.loc[suicide['State']==entered]
            #print(entered)
            #print(pun)
            to=pun["Total"].sum()
            statelabel=Label(master=root2,text="Total no. of Suicides from 2001-12 are :",font=('Times New Roman',15),fg="black")#,command=year) 
            statelabel.place(x=10,y=200)
            statevar=Label(master=root2,text=to,font=('Times New Roman',30),fg="black")#,command=year) 
            statevar.place(x=350,y=200)
            statebutton=Button(master=root2,text="Yearwise Graphical View",font=('Times New Roman',30),fg="black",command=stategraph) 
            statebutton.place(x=10,y=300)
            
        
            root.mainloop()
        root2=tk.Tk()
        root2.geometry('600x600')
        states=Label(master=root2,text="Enter State Name :  ",font=('Times New Roman',20),fg="black")#,command=year) 
        states.place(x=10,y=50)
        statese=Entry(master=root2,font=('Times New Roman',20)) 
        statese.place(x=250,y=50)
        statel=Button(master=root2,text="Find",font=('Times New Roman',20),fg="black",command=analysis) 
        statel.place(x=450,y=90)
        statelabel=Label(master=root2,text="Total no. of Suicides are :",font=('Times New Roman',30),fg="black")#,command=year) 
        #statelabel.place(x=10,y=200)
        statevar=Label(master=root2,text="Total no. of Suicides are :",font=('Times New Roman',30),fg="black")#,command=year) 
        #statevar.place(x=420,y=200)
        #statebutton=Label(master=root2,text="Yearwise Graphical View",font=('Times New Roman',30),fg="black")#,command=year) 
        #statebutton.place(x=10,y=300)
        root,mainloop()
    def year():
        def analyse():
            def yeargraph():
                num=two.groupby('State')['Total'].sum()
                num.plot(kind='bar')
                plt.title("Yearwise Analysis of Suicide")
                plt.xlabel("Year")
                plt.ylabel("Suicides")
                plt.show()
                root.mainloop()
            enter=int(yeare.get())
            two=suicide.loc[suicide['Year']==enter]
            #print(two)
            number=two["Total"].sum()
            #print("Total no.Suicides in ",enter,"are :",number) 
            '''age=suicide.loc[suicide["Age_group"]==0-14]
            print(age)
            age1=suicide.loc[suicide["Age_group"]==0-14]
            print(age1)
            age2=suicide.loc[suicide["Age_group"]==0-14]
            print(age2)
            age3=suicide.loc[suicide["Age_group"]==0-14]
            print(age3)'''
            yearlabel=Label(master=root1,text="Total no. of Suicides are :",font=('Times New Roman',30),fg="black")#,command=year) 
            yearlabel.place(x=10,y=200)
            yearvar=Label(master=root1,text=number,font=('Times New Roman',40),fg="black")#,command=year) 
            yearvar.place(x=420,y=200)
            yearbutton=Button(master=root1,text="Statewise Graphical View",font=('Times New Roman',25),fg="black",command=yeargraph) 
            yearbutton.place(x=10,y=300)
            #num=two.groupby('State')['Total'].sum()
            #num.plot(kind='bar')
            #plt.show()
            #print(num)
            root.mainloop()
        root1=tk .Tk()
        root1.geometry('600x600')
        years=Label(master=root1,text="Choose Year Name :  ",font=('Times New Roman',20),fg="black")#,command=year) 
        years.place(x=10,y=50)
        yeare=Spinbox(master=root1,from_=2001,to=2012,font=('Times New Roman',20)) 
        yeare.place(x=250,y=50)
        yearl=Button(master=root1,text="Find",font=('Times New Roman',20),fg="black",command=analyse) 
        yearl.place(x=450,y=90)
        #enter=int(yeare.get())
        #two=suicide.loc[suicide['Year']==enter]
        #print(two)
        root.mainloop()
    label.destroy()
    b2.destroy()
    b3.destroy()
    b4.destroy()
    
    bg1_image="torture.png"
    photo1=PhotoImage(file=bg1_image)
    label1=Label(image=photo1)
    label1.place(x=500,y=100)
    yearwise=Button(master=root,text="Yearwise Analysis",font=('Times New Roman',20),fg="black",command=year) 
    yearwise.place(x=100,y=50)
    statewise=Button(master=root,text="Statewise Analysis",font=('Times New Roman',20),fg="black",command=state) 
    statewise.place(x=100,y=150)
    reasonwise=Button(master=root,text="Reasons Analysis",font=('Times New Roman',20),fg="black",command=reason) 
    reasonwise.place(x=100,y=250)
    genderwise=Button(master=root,text="Genderwise Analysis",font=('Times New Roman',20),fg="black",command=gender) 
    genderwise.place(x=100,y=350)
    agegroupwise=Button(master=root,text="Age Group Analysis",font=('Times New Roman',20),fg="black",command=ageg) 
    agegroupwise.place(x=100,y=450)
    profession=Button(master=root,text="Professions Analysis",font=('Times New Roman',20),fg="black",command=profession) 
    profession.place(x=100,y=550)
    root.mainloop()
    #b4=Button(master=root,text="Continue",font=('Papyrus',20),fg="black",command=first) 
    #b4.place(x=700,y=600)
bg_image="suicide.png"
photo=PhotoImage(file=bg_image)
label=Label(image=photo)
label.place(x=0,y=150)
b2=Label(master=root,text="in  INDIA",font=('Papyrus',30),fg="black")#,command=page) 
b2.place(x=500,y=320)
b3=Label(master=root,text="2001-2012",font=('Papyrus',50),fg="black")#,command=page) 
b3.place(x=300,y=400)
b4=Button(master=root,text="Continue",font=('Papyrus',20),fg="black",command=first) 
b4.place(x=700,y=600)
root.mainloop()
